WorkShop4_MVC/WorkShop4_MVC/Controllers/BookManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookManagement.Controllers
{
    public class BookManagementController : Controller
    {
        // GET: BookManagement
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult GetBookClassToDrop()
        {
            Models.BookMangementService bookManagement = new Models.BookMangementService();
            List<SelectListItem> bookClass = bookManagement.GetAllBookClassName();
            return Json(bookClass);
        }
        [HttpPost]
        public JsonResult GetBookStatusToDrop()  //**命名應該不用加All，除非有其他會用到取個別的BookStatus
        {
            Models.BookMangementService bookManagement = new Models.BookMangementService();
            List<SelectListItem> bookKeeper = bookManagement.GetAllBookStatus();
            return Json(bookKeeper);
        }
        [HttpPost]
        public JsonResult GetMemberNameToDrop()
        {
            Models.BookMangementService bookManagement = new Models.BookMangementService();
            List<SelectListItem> bookKeeper = bookManagement.GetAllMemberName(); //**CName代表中文名字，但是要求是要英文+中文，並且搜尋結果中的只要顯示英文名字，所以這樣別人在看的時候會混淆
            return Json(bookKeeper);
        }
        [HttpPost]
        public JsonResult GetGridData(Models.SearchBookStatusArg arg)
        {
            Models.BookMangementService bookMangement = new Models.BookMangementService();
            List<Models.SearchBookStatusResult> GridData = bookMangement.GetSearchResultByCondition(arg);
            return Json(GridData);
        }

        [HttpGet]
        public ActionResult AddBook()    //**action 的名字會發現Index是大寫而addBook是駱駝命名 所以不好，visual studio預設是pascal命名，因此會有小灰點在addBook
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBook(Models.AddBookArg arg)  //回傳Json到前端在導向其他頁面
        {
            Models.BookMangementService bookMangement = new Models.BookMangementService();
            {
                if (ModelState.IsValid)
                {
                    string BookID = bookMangement.InsertBookData(arg).ToString();    //**BookID用來作為導向明細頁面的索引值
                    return RedirectToAction("Detail", new { BookID });
                }
            }
            return View(arg);
        }
        [HttpPost]
        public JsonResult DeleteBook(string BookId)
        {
            try
            {
                Models.BookMangementService bookMangementService = new Models.BookMangementService();
                bool deleteSuccess = bookMangementService.DeleteBookDataById(BookId);
                if (deleteSuccess)
                {
                    return this.Json(true);
                }
                else
                {
                    return this.Json(false);
                }
            }
            catch (Exception ex)
            {
                return this.Json(false);
            }
        }
        [HttpGet]     //Detail的參數用string 是不是比較好
        public ActionResult Detail(string BookId)       //**lookDetail -> Detail 因為lookDetail命名怪怪的
        {                                                   //**查看明細的時候將網址列的 ?bookId=A，會跳出錯誤，
                                                            //**因為資料庫中的 BOOK_ID 屬性是 int，GetBookDetails()裏面對資料庫的存取會出錯
                                                            //**所以用try catch包起來ex就會有錯誤訊息，網頁就不會當掉
                   //BookId 甚麼時候轉型比較好，Detail的參數是int，那參數是string的時候不會進來
            try
            {
                Models.BookMangementService bookMangementService = new Models.BookMangementService();
                Models.BookData bookData = bookMangementService.GetBookDetails(BookId).FirstOrDefault();
                return View("Detail", bookData);
            }
            catch (Exception ex)
            {
                return View("Index");
            }
        }
        /// <summary>
        /// 修改圖書的畫面
        /// </summary>
        /// <param name="BookId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult UpdateBook(string BookId)
        {
            Models.BookMangementService bookMangementService = new Models.BookMangementService();
            Models.BookData bookData = bookMangementService.GetBookData(BookId).FirstOrDefault();
            return View(bookData);
        }
        /// <summary>
        /// 修改圖書存檔
        /// </summary>
        /// <param name="bookData"></param>
        /// <returns></returns>
        [HttpPost]    //**會和使用者直接接觸的Action參數型別用string是不是比較好?
        public ActionResult UpdateBook(Models.BookData bookData)
        {
            Models.BookMangementService bookMangementService = new Models.BookMangementService();
            if (ModelState.IsValid)
            {
                try
                {
                    DateTime.Parse(bookData.BookBoughtDate);
                    bookMangementService.UpdateBookData(bookData);
                    return RedirectToAction("Detail", new { bookData.BookId });

                }catch(Exception ex)
                {
                    Response.Write("<script language=javascript>alert('日期格式錯誤')</script>");
                }
            }
            return View(bookData);
        }
    }
}

WorkShop4_MVC/WorkShop4_MVC/Views/BookManagement/AddBook.cshtml
@model BookManagement.Models.AddBookArg
@{
    ViewBag.Title = "AddBook";
}

<h2>新增書籍</h2>
<form asp-controller="BookMangement" asp-action="AddBook" method="post">
    <div class="form-horizontal">
        <div class="form-group">
            <label for="input_book_name" class="control-label col-md-2 required">書名</label>
            <div class="col-md-10">
                <input id="input_book_name" class="form-control" type="text" name="BookName" data-val-required="此欄位必填" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="input_book_author" class="control-label col-md-2 required">作者</label>
            <div class="col-md-10">
                <input id="input_book_author" class="form-control" type="text" name="BookAuthor" data-val-required="此欄位必填" required/>
                @*<span class="field-validation-valid text-danger" data-valmsg-for="input_book_author" data-valmsg-replace="true"></span>*@
            </div>
        </div>
        <div class="form-group">
            <label for="input_book_publisher" class="control-label col-md-2 required">出版商</label>
            <div class="col-md-10">
                <input id="input_book_publisher" class="form-control" type="text" name="BookPublisher" data-val-required="此欄位必填" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="input_book_note" class="control-label col-md-2 required">內容簡介</label>
            <div class="col-md-10">
                <textarea id="input_book_note" class="form-control" name="BookNote" maxlength="1000" rows="10" cols="10" placeholder="最多輸入1000字..." data-val-required="此欄位必填" required></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="input_book_bought_date" class="control-label col-md-2 required">購書日期</label>
            <div class="col-md-10">
                <input id="input_book_bought_date" class="form-control" type="date" name="BookBoughtDate" data-val-required="此欄位必填" required/>
            </div>
        </div>
        <div class="form-group">
            <label for="drop_book_class" class="control-label col-md-2 required">圖書類別</label>
            <div class="col-md-10">
                <input id="drop_book_class" class="form-control" type="text" name="BookClass" data-val-required="此欄位必填" required/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
            </div>
            <div class="col-md-10">
                <input type="submit" id="btn_add_book_data" name="新增" />
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {   
        $("#drop_book_class").kendoDropDownList({
                dataTextField: "Text",
                dataValueField: "Value",
                dataSource: {
                    transport: {
                        read: {
                            dataType: "Json",
                            url: "/bookManagement/GetBookClassToDrop",
                            type: "Post"
                        }
                    }
                }
        })
    });
</script>

WorkShop4_MVC/WorkShop4_MVC/Views/BookManagement/Detail.cshtml
@model BookManagement.Models.BookData

@{
    ViewBag.Title = "Detail";
}

<h2>圖書明細</h2>

<div>
    <h4>圖書明細</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            書名
        </dt>

        <dd>
            @Model.BookName
        </dd>

        <dt>
           作者
        </dt>

        <dd>
            @Model.BookAuthor
        </dd>

        <dt>
           出版商
        </dt>

        <dd>
           @Model.BookPublisher
        </dd>

        <dt>
            內容簡介
        </dt>

        <dd>
            @Model.BookNote
        </dd>

        <dt>
            購書日期
        </dt>

        <dd>
            @Model.BookBoughtDate
        </dd>

        <dt>
            圖書類別
        </dt>

        <dd>
           @Model.BookClassName
        </dd>

        <dt>
            借閱狀態
        </dt>

        <dd>
            @Model.BookStatusName
        </dd>

        <dt>
            借閱人
        </dt>

        <dd>
            @Model.BookKeeper
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WorkShop4_MVC/WorkShop4_MVC/Views/BookManagement/Index.cshtml
@model BookManagement.Models.SearchBookStatusArg
@{
    ViewBag.Title = "Index";
}

<h2>查詢畫面</h2>

<div class="form-horizontal">
    <div class="form-group">
        <label for="input_book_name" class="control-label col-md-2">書名</label>
        <div class="col-md-10">
            <input id="input_book_name" class="form-control" type="text" name="BookName" />
        </div>
    </div>

    <div class="form-group">
        <label for="drop_book_class" class="control-label col-md-2">圖書類別</label>
        <div class="col-md-10">
            <input id="drop_book_class" class="form-control" type="text" name="BookClass" />
        </div>
    </div>

    <div class="form-group">
        <label for="drop_book_keeper" class="control-label col-md-2">借閱人</label>
        <div class="col-md-10">
            <input id="drop_book_keeper" class="form-control" type="text" name="BookKeeper" />
        </div>
    </div>

    <div class="form-group">
        <label for="drop_book_status" class="control-label col-md-2">借閱狀態</label>
        <div class="col-md-10">
            <input id="drop_book_status" class="form-control" type="text" name="BookStatus" />
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <button id="btn_get_book_data">查詢</button>
            <button id="btn_add" onclick="Add()">新增</button>
        </div>
    </div>
    <div id="grid"></div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#drop_book_status").kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            optionLabel: " ",
            dataSource: {
                transport: {
                    read: {
                        dataType: "json",
                        url: "/bookManagement/GetBookStatusToDrop",  //Aciton 命名GetBookStatus
                        type: "Post"
                    }
                }
            },

        });
        $("#drop_book_class").kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            optionLabel: " ",
            dataSource: {
                transport: {
                    read: {
                        dataType: "json",
                        url: "/bookManagement/GetBookClassToDrop",
                        type: "Post"
                    }
                }
            }
        });
        $("#drop_book_keeper").kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            optionLabel: " ",
            dataSource: {
                transport: {
                    read: {
                        dataType: "Json",
                        url: "/bookManagement/GetMemberNameToDrop",
                        type: "Post"
                        
                    }
                }
            }
        });
        //查詢    點一下查詢會產生一個kendoGrid 應該要先做好kendoGrid，按下查詢後再將dataSource傳入
        $("#btn_get_book_data").click(function () {
            $.ajax({
                url: "/bookManagement/GetGridData",
                dataType: "json",
                type:"POST",
                data: {
                    "BookName": $("#input_book_name").val(),
                    "BookClass": $("#drop_book_class").val(),
                    "BookKeeperID": $("#drop_book_keeper").val(),
                    "BookStatus": $("#drop_book_status").val()
                }
            }).done(function (searchResult) {
                    $("#grid").kendoGrid({
                        dataSource: {
                            data: searchResult,
                            schema: {
                                model: {
                                    fields: {
                                        BookId: { type: "int" },
                                        BookClass: { type: "string" },
                                        BookName: { type: "string" },
                                        BookBoughtDate: { type: "string" },
                                        BookStatus: { type: "string" },
                                        BookKeeper: {type:"string"}
                                    }
                                }
                            }
                        },
                        height: 500,
                        columns: [
                            { hidden: true, field: "BookId", title: "書籍代碼" },
                            { field: "BookClass", title: "圖書類別", width: "20%" },
                            { field: "BookName", title: "書名", width: "40%" },
                            { field: "BookBoughtDate", title: "購書日期", width: "15%" },
                            { field: "BookStatus", title: "借閱狀態", width: "15%" },
                            { field: "BookKeeper", title: "借閱人", width: "10%" },
                            {
                                command: { text: "刪除", click: deleteBook },
                                title: " ",
                                width: "120px"
                            },
                            {
                                command: { text: "借閱紀錄", click: Record },
                                title: " ",
                                width: "120px"
                            },
                            {
                                command: { text: "編輯", click: updateBook },
                                title: " ",
                                width: "120px"
                            }
                        ]
                    })
                })
        })
    });
    //產生下拉選單函數
    function produceDropDownList(selector, url) {
        $(selector).kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            optionLabel: " ",
            dataSource: {
                transport: {
                    read: {
                        dataType: "Json",
                        url: "/bookManagement/" + url,
                        type: "Post"

                    }
                }
            }
        });
    }
    //跳到新增頁面
    function Add() {
        //$.get('/BookManagement/AddBook')
        location.href = '/BookManagement/AddBook'
    }
    //刪除書籍   **kendoGrid的dataSource還沒做清除，試試 .dataSource.read()  .dataSource.data([newDataSource]) 讓kendoGrid更新
    function deleteBook(e) {
        e.preventDefault();
        if (confirm("是否刪除")) {      
            var tr = $(e.target).closest("tr");   
            var rowId = this.dataItem(tr).BookId;         
            localStorage.setItem("BookId", rowId);
            $.ajax({
                type: "POST",
                url: "/BookManagement/DeleteBook",
                data: "BookId=" + localStorage.getItem("BookId"),
                dataType: "json",
                success: function (response) {
                    if (response == true) {
                        $(tr).remove();
                        alert("刪除成功")
                    } else {
                        alert("無法刪除")
                    }

                }, error: function (error) {
                    alert("系統錯誤");
                }
            });
            return false;
        }
    }
    //修改
    function updateBook(e) {
        e.preventDefault();
        var tr = $(e.target).closest("tr");
        var rowId = this.dataItem(tr).BookId;        ///rowId 
        location.href = "/BookManagement/UpdateBook?BookId=" + rowId;
    }
    //借閱紀錄
    function Record() {

    }
</script>

WorkShop4_MVC/WorkShop4_MVC/Views/BookManagement/UpdateBook.cshtml
@model BookManagement.Models.BookData
@{
    ViewBag.Title = "UpdateBook";
}
<h2 style="font-family:Microsoft JhengHei;">修改圖書</h2>
<form asp-controller="BookManagement" asp-action="UpdateBook" method="post">
    @*@Html.AntiForgeryToken()*@

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label for="inpu_book_name" class="control-label col-md-2 required">書名</label>
            <div class="col-md-10">
                <input id="inpu_book_name" class="form-control" type="text" name="BookName" value="@Model.BookName" />
            </div>
        </div>

        <div class="form-group">
            <label for="input_book_author" class="control-label col-md-2 required">作者</label>
            <div class="col-md-10">
                <input id="input_book_author" class="form-control" type="text" name="BookAuthor" value="@Model.BookAuthor" required/>
            </div>
        </div>

        <div class="form-group">
            <label for="input_book_publisher" class="control-label col-md-2 required">出版商</label>
            <div class="col-md-10">
                <input id="input_book_publisher" class="form-control" type="text" name="BookPublisher" value="@Model.BookPublisher" required/>
            </div>
        </div>

        <div class="form-group">
            <label for="input_book_note" class="control-label col-md-2 required">內容簡介</label>
            <div class="col-md-10">
                <textarea id="input_book_note" class="form-control" name="BookNote" maxlength="1000" rows="10" cols="10" placeholder="最多輸入1000字..." required>@Model.BookNote</textarea>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label for="input_book_bought_date" class="control-label col-md-2 required">購書日期</label>
        <div class="col-md-10">
            <input id="input_book_bought_date" class="form-control" type="date" name="BookBoughtDate" value="@Model.BookBoughtDate" required/>
        </div>
    </div>

    <div class="form-group">
        <label for="drop_book_class" class="control-label col-md-2 required">圖書類別</label>
        <div class="col-md-10">
            <input id="drop_book_class" type="text" class="form-control" onchange="changeClass(this)" name="BookClassId" value="@Model.BookClassId" required/>
            <input id="hidden_book_class_Id" type="hidden" name="BookClassName" value="@Model.BookClassName"/>
        </div>
    </div>

    <div class="form-group">
        <label for="drop_book_status" class="control-label col-md-2 required">借閱狀態</label>
        <div class="col-md-10">
            <input id="drop_book_status" type="text" class="form-control" name="BookStatusId" value="@Model.BookStatusId" required/>
        </div>
    </div>

    <div class="form-group">
        <label for="drop_book_keeper" class="control-label col-md-2">借閱人</label>
        <div class="col-md-10">
            <input id="drop_book_keeper" type="text" class="form-control" name="BookKeeper" value="@Model.BookKeeper"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn" value="存檔" style="background-color: #99b2db; color:#194284" />
            <input type="button" class="btn" id="delete" value="刪除" href="#" style="background-color: #99b2db; color:#194284">
            <input class="hidBookID" type="hidden" value='@Model.BookId' />
        </div>
    </div>

</form>
<div>
    <input type="button" value="返回" onclick="location.href='/BookManagement/Index'" class="btn" style="background-color: #99b2db; color:#194284" />
</div>

<script>  ///
    $(document).ready(function () {
        $("#drop_book_status").kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            dataSource: {
                transport: {
                    read: {
                        dataType: "json",
                        url: "/bookManagement/GetBookStatusToDrop",
                        type: "Post"
                    }
                }
            },
            change: changeStatus
        });
        $("#drop_book_class").kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            dataSource: {
                transport: {
                    read: {
                        dataType: "json",
                        url: "/bookManagement/GetBookClassToDrop",
                        type: "Post"
                    }
                }
            }
        });
        $("#drop_book_keeper").kendoDropDownList({
            dataTextField: "Text",
            dataValueField: "Value",
            dataSource: {
                transport: {
                    read: {
                        dataType: "json",
                        url: "/bookManagement/GetMemberNameToDrop",
                        type: "Post"
                    }
                }
            }
        });
        //控制借閱狀態與借閱人欄位關聯    後端還沒有防治 F12下 $("#drop_book_keeper").data("kendoDropDownList").value("");
        var check = $("#drop_book_status").val();
        if (check == "A" || check == "U") {
            $("#drop_book_keeper").data("kendoDropDownList").enable(false);
            $("#drop_book_keeper").data("kendoDropDownList").value("");

        }
        else if (check == "B" || check == "C") {
            $("#drop_book_keeper").data("kendoDropDownList").enable(true);
        }
        //刪除書籍
        $("#delete").click(function (e) {
            if (confirm('確定是否刪除這筆紀錄?')) {
                e.preventDefault();
                $.ajax({
                    type: "POST",
                    url: "/bookManagement/DeleteBook",
                    data: "BookId=" + @Model.BookId,
                    dataType: "json",
                    success: function (response) {
                        if (response == true) { 
                            alert("圖書已刪除");
                            location.href = '/BookManagement/Index'
                        }
                        else {
                            alert("圖書已借出");
                        }
                    },
                    error: function (error) {
                        alert("系統發生錯誤");
                    }
                });
            }
        });
    });       
    //書籍類別更改同時更改model.BookClassId
    function changeClass(e) {  
        $(":hidden#hidden_book_class_Id").value = $("#drop_book_status").data("kendoDropDownList").value();
    }   
    //控制借閱狀態與借閱人欄位關聯
    function changeStatus(e) {
        e.preventDefault();
        var Check = $("#drop_book_status").data("kendoDropDownList").value();
        if (Check == "A" || Check == "U") {
            $("#drop_book_keeper").data("kendoDropDownList").enable(false);
            $("#drop_book_keeper").data("kendoDropDownList").value("");
            
        }
        else if (Check == "B" || Check == "C") {
            $("#drop_book_keeper").data("kendoDropDownList").value("0001");
            $("#drop_book_keeper").data("kendoDropDownList").enable(true);
        }
    }
</script>